## `terraform apply` for `{{ .Env.TF_NAME }}/terraform.tfplan`

This GitHub Workflow has applied the execution plan for the configuration in [`{{ .Env.TF_NAME }}`][configuration] by running `terraform apply` using the `terraform.tfplan` generated by the previous `terraform plan` step. The summary is as follows:

```plain
{{ printf "%d resources added, %d changed, and %d destroyed."
    (ds "terraform").Changes.Added
    (ds "terraform").Changes.Changed
    (ds "terraform").Changes.Destroyed
}}
```

The full log showing all the changes applied by Terraform, is included
below (click below to expand and view the `apply` log):

<details>
<summary>
  <code>terraform apply {{ .Env.TF_NAME }}/terraform.tfplan</code> Output
</summary>

```plain
{{ (print (getenv "TF_PATH") "/.terraform/apply.log") | file.Read | strings.TrimSpace }}
```

</details>

[configuration]: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/tree/{{ getenv "GITHUB_HEAD_REF" }}/{{ if (ne .Env.TF_NAME ".") }}{{ .Env.TF_NAME }}/{{ end }}

{{- /* vim:set ft=markdown wrap linebreak tw=0: */ -}}
